name: Deploy To Azure App Service

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js Version
        uses: actions/setup-node@v4
      with:
        node-version: '18.x'
      - name: Install Dependencies
        run: npm install
        working-directory: ./backend
      - name: Deploy To Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: events-mgr
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
      CI: true